apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-httpecho.yaml
  - deployment-envoy.yaml
  - sa.yaml

configMapGenerator:
  - name: envoy-config
    behavior: create
    files:
      - envoy.yaml

generatorOptions:
  disableNameSuffixHash: true

