apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:oidc-discovery
rules:
  - nonResourceURLs:
      - /.well-known/openid-configuration
      - /openid/v1/jwks
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:oidc-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:oidc-discovery
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:unauthenticated
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
